### PR TITLE
[SERV-467] Enable configuration of access cookie domain

### PR DESCRIPTION
**Pull request by markmatney**
In our case, we would use:
```
ACCESS_COOKIE_DOMAIN=iiif.library.ucla.edu
```

### CODE REVIEW

**Comment by cachemeoutside** [comment]
Re: ACCESS_COOKIE_DOMAIN, does this have to be set on both Cantaloupe and HAuth?

**Comment by markmatney** [comment]
just Hauth

**Comment by markmatney** [comment]
WIll mark as draft until #41 is merged, then I'll rebase and the Snyk check should pass.

**Review by cachemeoutside — APPROVED** [review]
Not a java guy, but looks like a fairly straightforward change as I'm able to understand the logic changes.

**Review by DRickard — APPROVED** [review]

**Review by ksclarke — APPROVED** [review]

**Pull request merged**
