### PR TITLE
[IIIF-1179] Add Redis container and a trivial test to the build

### PR DESCRIPTION
**Pull request by markmatney**

### CODE REVIEW

**Review by ksclarke — COMMENTED** [review]
All this looks good. Since we've gone back to psql now, we'll want redis to serve as a cache for that. Do you want to figure out the connectivity piece now or create a new ticket for that?

**Review by DRickard — APPROVED** [review]

**Comment by markmatney** [comment]
I am inclined to say new ticket

**Comment by ksclarke** [comment]
> I am inclined to say new ticket

Okay, would you create that and assign it to the same epic?

**Review by ksclarke — APPROVED** [review]

**Comment by markmatney** [comment]
IIIF-1179

**Pull request merged**
